# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: eoli3n
subtitle: … Blog …
logo: avatar.png
email: jonathan.kirszling@runbox.com
description: "A blog that talks about Linux, Pizza, DevOps and more."
message: "Reach me on irc.libera.chat #archlinux-fr or #voidlinux."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eoli3n.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Social icons
twitter_url:
facebook_url:
googleplus_url:
instagram_url:
linkedin_url:
github_url: https://github.com/eoli3n
pizza_url: https://photos.google.com/share/AF1QipOwuYXLCoWlUpS7sk2UiT1-xFopAaeXYT21rPl9iKjNl2txOxwc3vpCIknVYpRf1w?key=RnNVSUxvQWkyTzdvSnBURXVZMWpGbVpXcTZnbEFn
bread_url: https://photos.google.com/share/AF1QipO7ZE4k_K7VpfrDcQ6pXZc3URXhCuIHF4aZ3iYFZ26G6wpC5and65WkXzfl-Ctsnw?key=UGdsSDAwanlOV1BkaU5WZ0p3MWI0VGFlRzJwdXdR
stackoverflow_url: https://stackoverflow.com/users/11061370/eoli3n
pinterest_url:
slack_url:
dribbble_url:
asciinema_url: https://asciinema.org/~eoli3n
reddit_url: https://www.reddit.com/user/eoli3n

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

kramdown:
  input: GFM
  hard_wrap : true
  syntax_highlighter_opts:
    default_lang: bash

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - vendor
  - INSTALL.md
  - TODO.md
  - archzfs
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
